addSbtPlugin("se.marcuslonnberg" % "sbt-docker"     % "1.8.2")
addSbtPlugin("com.eed3si9n"      % "sbt-assembly"   % "0.15.0")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"  % "0.10.0")
addSbtPlugin("com.scalapenos"    % "sbt-prompt"     % "1.0.2")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"   % "2.4.6")
addSbtPlugin("de.heikoseeberger" % "sbt-header"     % "5.0.0")
addSbtPlugin("com.cavorite"      % "sbt-avro-1-9"   % "1.1.9")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"   % "0.10.4")
