addSbtPlugin("se.marcuslonnberg" % "sbt-docker"  % "1.5.0")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.10")
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.9.0")
addSbtPlugin("com.scalapenos" % "sbt-prompt" % "1.0.2")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.3.0")
addSbtPlugin("com.cavorite" % "sbt-avro-1-9" % "1.1.7")
addSbtPlugin("de.heikoseeberger"  % "sbt-header" % "5.0.0")